create table "public"."leagues" (
    "id" integer generated by default as identity not null,
    "fpl_id" bigint not null,
    "season" character varying not null,
    "created_at" timestamp with time zone default now()
);


-- alter table "public"."leagues" enable row level security;

-- CREATE POLICY "Allow creating leagues"
--   ON "public"."leagues"
--   FOR INSERT
--   TO PUBLIC
--   WITH CHECK (true);

create table "public"."match_results" (
    "id" bigint generated by default as identity not null,
    "points" smallint not null,
    "match_id" bigint not null,
    "team_id" bigint,
    "opponent_id" bigint,
    "created_at" timestamp with time zone default now()
);


-- alter table "public"."match_results" enable row level security;

create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "league_id" integer,
    "gameweek" integer not null,
    "status" numeric not null default '0'::numeric,
    "created_at" timestamp with time zone default now()
);


-- alter table "public"."matches" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "fpl_id" integer not null,
    "entry_id" integer not null,
    "name" character varying not null,
    "manager" integer not null,
    "league_id" integer
);

-- alter table "public"."teams" enable row level security;

CREATE POLICY "Allow creating teams"
  ON "public"."teams"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE UNIQUE INDEX leagues_fpl_id_key ON public.leagues USING btree (fpl_id);

CREATE UNIQUE INDEX leagues_pkey ON public.leagues USING btree (id);

CREATE UNIQUE INDEX match_results_pkey ON public.match_results USING btree (id);

CREATE UNIQUE INDEX match_results_team_id_match_id_key ON public.match_results USING btree (team_id, match_id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX teams_entry_id_key ON public.teams USING btree (entry_id);

CREATE UNIQUE INDEX teams_fpl_id_key ON public.teams USING btree (fpl_id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

alter table "public"."leagues" add constraint "leagues_pkey" PRIMARY KEY using index "leagues_pkey";

alter table "public"."match_results" add constraint "match_results_pkey" PRIMARY KEY using index "match_results_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."leagues" add constraint "leagues_fpl_id_key" UNIQUE using index "leagues_fpl_id_key";

alter table "public"."match_results" add constraint "match_results_match_id_fkey" FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE not valid;

alter table "public"."match_results" add constraint "match_results_team_id_match_id_key" UNIQUE using index "match_results_team_id_match_id_key";

alter table "public"."match_results" validate constraint "match_results_match_id_fkey";

alter table "public"."match_results" add constraint "match_results_opponent_id_fkey" FOREIGN KEY (opponent_id) REFERENCES match_results(id) ON DELETE CASCADE not valid;

alter table "public"."match_results" validate constraint "match_results_opponent_id_fkey";

alter table "public"."match_results" add constraint "match_results_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."match_results" validate constraint "match_results_team_id_fkey";

alter table "public"."matches" add constraint "matches_league_id_fkey" FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "matches_league_id_fkey";

alter table "public"."teams" add constraint "teams_entry_id_key" UNIQUE using index "teams_entry_id_key";

alter table "public"."teams" add constraint "teams_fpl_id_key" UNIQUE using index "teams_fpl_id_key";

alter table "public"."teams" add constraint "teams_league_id_fkey" FOREIGN KEY (league_id) REFERENCES leagues(id) ON DELETE CASCADE not valid;

alter table "public"."teams" validate constraint "teams_league_id_fkey";